# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('title', models.CharField(help_text='Ej: Dia 1 - Inauguracion', max_length=255, verbose_name='titulo')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'dia del cronograma',
                'verbose_name_plural': 'dias del cronograma',
                'db_table': 'schedule_days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titulo')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripcion')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de fin')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='ubicacion')),
                ('item_type', models.CharField(choices=[('conference', 'Conferencia'), ('workshop', 'Taller'), ('break', 'Receso'), ('ceremony', 'Ceremonia'), ('social', 'Social')], db_index=True, default='conference', max_length=20, verbose_name='tipo')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='destacado')),
                ('order', models.PositiveIntegerField(default=0, help_text='Para ordenar items con la misma hora de inicio.', verbose_name='orden')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schedule.scheduleday', verbose_name='dia')),
            ],
            options={
                'verbose_name': 'actividad del cronograma',
                'verbose_name_plural': 'actividades del cronograma',
                'db_table': 'schedule_items',
                'ordering': ['day__date', 'start_time', 'order'],
            },
        ),
    ]
