# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='workshops.speaker', verbose_name='ponente'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='workshops.workshop', verbose_name='taller vinculado'),
        ),
    ]
