# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('bio', models.TextField(blank=True, default='', verbose_name='biografia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/photos/%Y/', verbose_name='foto')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='tema / especialidad')),
                ('organization', models.CharField(blank=True, default='', help_text='Universidad, empresa o institucion a la que pertenece.', max_length=255, verbose_name='organizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ponente',
                'verbose_name_plural': 'ponentes',
                'db_table': 'speakers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripcion')),
                ('workshop_type', models.CharField(choices=[('workshop', 'Taller'), ('talk', 'Charla'), ('technical_visit', 'Visita tecnica')], db_index=True, default='workshop', max_length=20, verbose_name='tipo')),
                ('start_time', models.DateTimeField(verbose_name='inicio')),
                ('end_time', models.DateTimeField(verbose_name='fin')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='ubicacion')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = sin limite.', verbose_name='capacidad')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='inscritos')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_ticket_types', models.ManyToManyField(blank=True, help_text='Dejar vacio si esta abierto a todos los tipos de entrada.', related_name='workshops', to='tickets.tickettype', verbose_name='tipos de entrada requeridos')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.speaker', verbose_name='ponente')),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
                'db_table': 'workshops',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inscripcion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workshops.workshop', verbose_name='taller')),
            ],
            options={
                'verbose_name': 'inscripcion a taller',
                'verbose_name_plural': 'inscripciones a talleres',
                'db_table': 'workshop_enrollments',
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'user'), name='unique_workshop_enrollment')],
            },
        ),
    ]
