# Generated by Django 5.2.12 on 2026-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CONEIC 2027', max_length=255, verbose_name='nombre del evento')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripcion')),
                ('edition', models.CharField(blank=True, default='', help_text='Ej: XXXII Edicion', max_length=50, verbose_name='edicion')),
                ('host_university', models.CharField(blank=True, default='', max_length=255, verbose_name='universidad sede')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ciudad')),
                ('country', models.CharField(default='Peru', max_length=100, verbose_name='pais')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('venue', models.CharField(blank=True, default='', max_length=255, verbose_name='sede / local')),
                ('mission', models.TextField(blank=True, default='', verbose_name='mision')),
                ('vision', models.TextField(blank=True, default='', verbose_name='vision')),
                ('history', models.TextField(blank=True, default='', verbose_name='historia')),
            ],
            options={
                'verbose_name': 'informacion del evento',
                'verbose_name_plural': 'informacion del evento',
                'db_table': 'event_info',
            },
        ),
        migrations.CreateModel(
            name='OrganizingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('role', models.CharField(max_length=255, verbose_name='cargo')),
                ('university', models.CharField(blank=True, default='', max_length=255, verbose_name='universidad')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='committee/photos/', verbose_name='foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'miembro del comite organizador',
                'verbose_name_plural': 'miembros del comite organizador',
                'db_table': 'organizing_committee',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='logo')),
                ('website', models.URLField(blank=True, default='', verbose_name='sitio web')),
                ('tier', models.CharField(choices=[('platinum', 'Platino'), ('gold', 'Oro'), ('silver', 'Plata'), ('bronze', 'Bronce'), ('media', 'Media Partner')], db_index=True, default='bronze', max_length=20, verbose_name='nivel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'patrocinador',
                'verbose_name_plural': 'patrocinadores',
                'db_table': 'sponsors',
                'ordering': ['tier', 'order', 'name'],
            },
        ),
    ]
