# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='teléfono')),
                ('university', models.CharField(blank=True, default='', max_length=255, verbose_name='universidad')),
                ('career', models.CharField(blank=True, default='', max_length=255, verbose_name='carrera')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='país')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ciudad')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su correo electrónico.', verbose_name='verificado')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='token de verificación')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.', verbose_name='eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
