# Generated by Django 5.2.12 on 2026-03-27 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accredited', models.BooleanField(db_index=True, default=False, verbose_name='acreditado')),
                ('accredited_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de acreditacion')),
                ('qr_code', models.ImageField(blank=True, upload_to='participants/qr_codes/', verbose_name='codigo QR')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token QR')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='estado de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'db_table': 'participants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('student', 'Estudiante'), ('professional', 'Profesional'), ('speaker', 'Ponente'), ('organizer', 'Organizador')], max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'tipo de participante',
                'verbose_name_plural': 'tipos de participante',
                'db_table': 'participant_types',
                'ordering': ['name'],
            },
        ),
    ]
