# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('tickets', '0001_initial'),
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accredited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accreditations_made', to=settings.AUTH_USER_MODEL, verbose_name='acreditado por'),
        ),
        migrations.AddField(
            model_name='participant',
            name='selected_workshops',
            field=models.ManyToManyField(blank=True, related_name='participants', to='workshops.workshop', verbose_name='talleres seleccionados'),
        ),
        migrations.AddField(
            model_name='participant',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='tickets.ticket', verbose_name='ticket'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='participants.participanttype', verbose_name='tipo de participante'),
        ),
    ]
