# Generated by Django 5.2.12 on 2026-03-27 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('attendance', 'Asistencia'), ('workshop', 'Taller'), ('speaker', 'Ponente')], db_index=True, max_length=20, verbose_name='tipo de certificado')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de emision')),
                ('validation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='codigo de validacion')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='archivo PDF')),
                ('hours', models.PositiveIntegerField(default=8, help_text='Horas academicas certificadas.', verbose_name='horas')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
