# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='participants.participant', verbose_name='participante'),
        ),
    ]
