# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0002_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='workshop',
            field=models.ForeignKey(blank=True, help_text='Solo aplica para certificados de tipo taller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='workshops.workshop', verbose_name='taller'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('participant', 'certificate_type', 'workshop'), name='unique_certificate_per_participant_type_workshop'),
        ),
    ]
