# Generated by Django 5.2.12 on 2026-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto (PEN)')),
                ('currency', models.CharField(default='PEN', max_length=3, verbose_name='Moneda')),
                ('payment_method', models.CharField(choices=[('culqi', 'Tarjeta (Culqi)'), ('yape', 'Yape')], max_length=20, verbose_name='Metodo de pago')),
                ('culqi_charge_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ID de cargo Culqi')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Respuesta JSON completa de la API de Culqi.', verbose_name='Respuesta cruda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Registro de pago',
                'verbose_name_plural': 'Registros de pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
