# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_logs', to='tickets.ticket', verbose_name='Entrada'),
        ),
    ]
