# Generated by Django 5.2.12 on 2026-03-27 05:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Codigo de compra')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('culqi', 'Tarjeta (Culqi)'), ('yape', 'Yape')], max_length=20, verbose_name='Metodo de pago')),
                ('payment_reference', models.CharField(blank=True, default='', help_text='ID de cargo en Culqi u otra referencia externa.', max_length=255, verbose_name='Referencia de pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado (PEN)')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Comprobante PDF')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (PEN)')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Lista JSON de beneficios incluidos en este tipo de entrada.', verbose_name='Beneficios')),
                ('includes_workshops', models.BooleanField(default=False, verbose_name='Incluye talleres')),
                ('max_workshop_slots', models.PositiveIntegerField(default=0, help_text='Numero maximo de talleres a los que puede inscribirse.', verbose_name='Cupos de talleres')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad total')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Vendidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('available_until', models.DateTimeField(help_text='Fecha limite para adquirir este tipo de entrada.', verbose_name='Disponible hasta')),
            ],
            options={
                'verbose_name': 'Tipo de entrada',
                'verbose_name_plural': 'Tipos de entrada',
                'ordering': ['price'],
            },
        ),
    ]
